version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
             yarn : true    
             store_artifacts: true
           # record: true

        #  executor: cypress/base-14
        #  start: npm start        # start server  

# store test reports -->>
        #  post-steps:
        #     - store_test_results:
        #         path: cypress/results







